# Generated by Django 5.2.17 on 2026-09-07 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0038_product_product_status_publish_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement_type', models.CharField(choices=[('sprayer', 'سم\u200cپاش'), ('disc', 'دیسک'), ('plough', 'شخم\u200cزن'), ('seeder', 'بذرکار'), ('other', 'سایر ادوات')], db_index=True, default='other', max_length=20, verbose_name='نوع ادویت')),
                ('working_width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='عرض کار (متر)')),
                ('compatible_tractors', models.TextField(blank=True, help_text='متن آزاد؛ مثلاً: «جاندیر ۳۸۵، فرگوسن ۲۸۵، رومانی ۴۴۵»', verbose_name='تراکتورهای سازگار')),
                ('warranty_months', models.PositiveSmallIntegerField(default=0, verbose_name='گارانتی (ماه)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implement_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'ادوت کشاورزی',
                'verbose_name_plural': 'ادوات کشاورزی',
                'ordering': ('implement_type',),
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horsepower', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='اسب بخار')),
                ('manufacture_year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='سال ساخت')),
                ('working_hours', models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد')),
                ('warranty_months', models.PositiveSmallIntegerField(default=0, verbose_name='گارانتی (ماه)')),
                ('is_second_hand', models.BooleanField(db_index=True, default=False, verbose_name='دست دوم')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'تراکتور',
                'verbose_name_plural': 'تراکتورها',
                'ordering': ('-manufacture_year',),
                'indexes': [models.Index(fields=['is_second_hand', '-manufacture_year'], name='tractor_sh_year_idx')],
            },
        ),
    ]
