# Generated by Django 5.2.17 on 2026-09-07 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='سال شمسی یا میلادی ساخت؛ مثلاً ۱۴۰۱ یا ۲۰۲۳', validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(2100)], verbose_name='سال ساخت'),
        ),
    ]
