# Generated by Django 5.2.17 on 2026-09-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_alter_tractor_manufacture_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implement',
            options={'ordering': ('implement_type',), 'verbose_name': 'ادوات کشاورزی', 'verbose_name_plural': 'ادوات کشاورزی'},
        ),
        migrations.AlterField(
            model_name='implement',
            name='compatible_tractors',
            field=models.TextField(blank=True, help_text='متن آزاد؛ مثلاً: «جاندیر ۳۸۵، فرگوسن ۲۳۵، رومانی ۴۴۵»', verbose_name='تراکتورهای سازگار'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='implement_type',
            field=models.CharField(choices=[('sprayer', 'سم\u200cپاش'), ('disc', 'دیسک'), ('plough', 'شخم\u200cزن'), ('seeder', 'بذرکار'), ('other', 'سایر ادوات')], db_index=True, default='other', max_length=20, verbose_name='نوع ادوات'),
        ),
    ]
