# Generated by Django 5.2.17 on 2026-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_alter_implement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implement',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='گارانتی (ماه)'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='working_width',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=4, verbose_name='عرض کار (متر)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='گارانتی (ماه)'),
        ),
    ]
