# Generated by Django 5.2.17 on 2026-09-08 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0039_historicalorder_loyalty_refunded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, help_text='کدی که حامل روی رسید مرسوله درج می\u200cکند؛ کلید اصلی پیگیری مشتری.', max_length=64, unique=True, verbose_name='کد رهگیری')),
                ('carrier_name', models.CharField(max_length=100, verbose_name='نام حامل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پذیرش'), ('picked_up', 'تحویل به حامل شد'), ('in_transit', 'در مسیر'), ('out_for_delivery', 'در حال توزیع'), ('delivered', 'تحویل داده شد'), ('failed', 'تحویل ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی تحویل')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج از انبار')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_shipment', to='shop.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرسوله لجستیک',
                'verbose_name_plural': 'مرسوله\u200cهای لجستیک',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پذیرش'), ('picked_up', 'تحویل به حامل شد'), ('in_transit', 'در مسیر'), ('out_for_delivery', 'در حال توزیع'), ('delivered', 'تحویل داده شد'), ('failed', 'تحویل ناموفق')], max_length=20, verbose_name='وضعیت در این نقطه')),
                ('description', models.CharField(max_length=300, verbose_name='توضیح رویداد')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='مکان')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.shipment', verbose_name='مرسوله')),
            ],
            options={
                'verbose_name': 'رویداد رهگیری لجستیک',
                'verbose_name_plural': 'رویدادهای رهگیری لجستیک',
                'ordering': ('-timestamp', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'estimated_delivery_date'], name='logi_ship_status_eta_idx'),
        ),
    ]
