# Generated by Django 4.2.5 on 2025-12-04 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='دسته')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], default='male', max_length=15)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیردسته')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='SeedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100, verbose_name='نوع گیاه')),
                ('variety', models.CharField(max_length=100, verbose_name='رقم')),
                ('weight_per_kg', models.CharField(max_length=20, verbose_name='وزن در کیلوگرم')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات بذر',
                'verbose_name_plural': 'مشخصات بذر',
            },
        ),
        migrations.CreateModel(
            name='PesticideDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_type', models.CharField(max_length=100, verbose_name='نوع سم')),
                ('active_ingredient', models.CharField(max_length=100, verbose_name='مواد فعال')),
                ('concentration', models.CharField(max_length=20, verbose_name='غلظت (%)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات سم',
                'verbose_name_plural': 'مشخصات سم',
            },
        ),
        migrations.CreateModel(
            name='FertilizerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(max_length=100, verbose_name='نوع کود')),
                ('nitrogen', models.CharField(max_length=20, verbose_name='نیتروژن (%)')),
                ('phosphorus', models.CharField(max_length=20, verbose_name='فسفر (%)')),
                ('potassium', models.CharField(max_length=20, verbose_name='پتاسیم (%)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات کود',
                'verbose_name_plural': 'مشخصات کود',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=100, verbose_name='نوع ابزار')),
                ('material', models.CharField(max_length=100, verbose_name='جنس')),
                ('weight', models.CharField(max_length=20, verbose_name='وزن')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات ابزار',
                'verbose_name_plural': 'مشخصات ابزار',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.item')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
