# Generated by Django 5.2.17 on 2026-08-22 10:48

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_user_alter_equipmentdetail_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=shop.models.create_order_code, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='نام تحویل\u200cگیرنده')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('province', models.CharField(max_length=80, verbose_name='استان')),
                ('city', models.CharField(max_length=80, verbose_name='شهر')),
                ('address', models.TextField(max_length=500, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='توضیحات مشتری')),
                ('subtotal', models.PositiveBigIntegerField(default=0)),
                ('shipping_price', models.PositiveBigIntegerField(default=0)),
                ('total_price', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('awaiting_review', 'در انتظار بررسی'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], db_index=True, default='awaiting_review', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت وجه')], db_index=True, default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('coordination', 'هماهنگی با کارشناس'), ('zarinpal', 'پرداخت آنلاین زرین\u200cپال')], default='coordination', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('product_slug', models.SlugField(max_length=250)),
                ('unit_price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=shop.models.create_procurement_code, max_length=32, unique=True)),
                ('farmer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('crop_name', models.CharField(max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(default='کیلوگرم', max_length=30)),
                ('requested_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('province', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال ارزیابی'), ('offered', 'پیشنهاد ارسال شد'), ('contracted', 'قرارداد شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست خرید محصول کشاورز',
                'verbose_name_plural': 'درخواست\u200cهای خرید محصول کشاورز',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=shop.models.create_service_code, max_length=32, unique=True)),
                ('service_type', models.CharField(choices=[('agronomy', 'مشاوره زراعی'), ('irrigation', 'طراحی و نصب آبیاری'), ('soil', 'آزمایش و بهبود خاک'), ('greenhouse', 'گلخانه و کشت کنترل\u200cشده'), ('machinery', 'ماشین\u200cآلات و تعمیرات'), ('other', 'سایر خدمات')], max_length=20)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('crop', models.CharField(blank=True, max_length=120)),
                ('farm_area_hectare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('quoted', 'پیشنهاد ارسال شد'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست خدمت',
                'verbose_name_plural': 'درخواست\u200cهای خدمت',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('seller_type', models.CharField(choices=[('farmer', 'کشاورز'), ('cooperative', 'تعاونی'), ('merchant', 'تاجر'), ('company', 'شرکت')], default='farmer', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'غرفه',
                'verbose_name_plural': 'غرفه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('crop_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                ('price', models.PositiveBigIntegerField()),
                ('unit', models.CharField(default='کیلوگرم', max_length=30)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار تأیید'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('sold_out', 'اتمام موجودی'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shop.storefront')),
            ],
            options={
                'verbose_name': 'آگهی بازار کشاورزان',
                'verbose_name_plural': 'آگهی\u200cهای بازار کشاورزان',
                'ordering': ('-created_at',),
            },
        ),
    ]
