# Generated by Django 5.2.17 on 2026-08-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem_procurementrequest_servicerequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate_code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('coordination', 'هماهنگی با کارشناس'), ('zarinpal', 'زرین\u200cپال'), ('stripe_card', 'کارت بین\u200cالمللی از طریق Stripe'), ('paypal', 'PayPal'), ('crypto', 'پرداخت رمزارزی')], default='coordination', max_length=20),
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('active', 'فعال'), ('suspended', 'معلق')], db_index=True, default='pending', max_length=20)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'همکار فروش',
                'verbose_name_plural': 'همکاران فروش',
            },
        ),
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید پرداخت'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('paid_out', 'تسویه شده')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_conversion', to='shop.order')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='shop.affiliateprofile')),
            ],
            options={
                'verbose_name': 'تبدیل همکار فروش',
                'verbose_name_plural': 'تبدیل\u200cهای همکار فروش',
            },
        ),
        migrations.CreateModel(
            name='FinancialLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('platform', 'پلتفرم'), ('seller', 'فروشنده'), ('advisor', 'مشاور'), ('affiliate', 'همکار فروش')], max_length=20)),
                ('entry_type', models.CharField(choices=[('sale', 'فروش'), ('commission', 'کمیسیون'), ('consultation', 'مشاوره'), ('affiliate_commission', 'کمیسیون همکاری در فروش'), ('payout', 'تسویه'), ('refund', 'بازگشت وجه'), ('adjustment', 'اصلاحیه')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('available', 'قابل تسویه'), ('held', 'مسدود برای رسیدگی'), ('paid', 'تسویه شده'), ('reversed', 'برگشت خورده')], db_index=True, default='pending', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Positive for credit, negative for debit.')),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='shop.affiliateconversion')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='shop.order')),
                ('storefront', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='shop.storefront')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رکورد دفتر مالی',
                'verbose_name_plural': 'دفتر مالی',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('coordination', 'هماهنگی با کارشناس'), ('zarinpal', 'زرین\u200cپال'), ('stripe_card', 'کارت بین\u200cالمللی از طریق Stripe'), ('paypal', 'PayPal'), ('crypto', 'پرداخت رمزارزی')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('paid', 'پرداخت موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده'), ('refunded', 'بازگشت وجه')], db_index=True, default='created', max_length=20)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='shop.order')),
            ],
            options={
                'verbose_name': 'تلاش پرداخت',
                'verbose_name_plural': 'تلاش\u200cهای پرداخت',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('suggestion', 'پیشنهاد'), ('criticism', 'انتقاد'), ('consultation', 'درخواست راهنمایی'), ('other', 'سایر')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('resolved', 'رسیدگی شد')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازخورد پلتفرم',
                'verbose_name_plural': 'بازخوردهای پلتفرم',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorefrontComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('awaiting_response', 'در انتظار پاسخ فروشنده'), ('resolved', 'حل شده'), ('rejected', 'رد شده')], db_index=True, default='new', max_length=30)),
                ('resolution_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complainant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='shop.marketplacelisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_complaints', to='shop.order')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='shop.storefront')),
            ],
            options={
                'verbose_name': 'شکایت از غرفه',
                'verbose_name_plural': 'شکایت\u200cهای غرفه',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VisualSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visual-search/%Y/%m/')),
                ('target', models.CharField(choices=[('product', 'جستجوی محصول'), ('pest', 'تشخیص آفت/بیماری')], default='product', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحلیل'), ('processing', 'در حال تحلیل'), ('completed', 'تکمیل شده'), ('no_match', 'بدون نتیجه'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست جستجوی تصویری',
                'verbose_name_plural': 'درخواست\u200cهای جستجوی تصویری',
                'ordering': ('-created_at',),
            },
        ),
    ]
