# Generated by Django 5.2.17 on 2026-08-22 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_affiliate_code_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sticker',
            field=models.CharField(blank=True, max_length=16, verbose_name='استیکر'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20)),
                ('discount_value', models.PositiveBigIntegerField()),
                ('max_discount_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('min_order_amount', models.PositiveBigIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('issued_to_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorefrontPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('post', 'پست'), ('story', 'استوری')], default='post', max_length=12)),
                ('caption', models.TextField(max_length=2200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefront-posts/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='shop.marketplacelisting')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shop.storefront')),
            ],
            options={
                'verbose_name': 'پست غرفه',
                'verbose_name_plural': 'پست\u200cها و استوری\u200cهای غرفه',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Positive credits and negative debits.')),
                ('transaction_type', models.CharField(choices=[('loyalty_reward', 'پاداش وفاداری'), ('order_discount', 'تخفیف سفارش'), ('refund', 'بازگشت وجه'), ('affiliate_payout', 'تسویه همکاری در فروش'), ('seller_payout', 'تسویه فروشنده'), ('adjustment', 'اصلاحیه')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('available', 'قابل استفاده'), ('spent', 'مصرف شده'), ('reversed', 'برگشت خورده')], db_index=True, default='pending', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shop.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.wallet')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ('-created_at',),
            },
        ),
    ]
