# Generated by Django 5.2.17 on 2026-08-22 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_image_comment_sticker_order_coupon_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ مدیریتی',
                'verbose_name_plural': 'لاگ\u200cهای مدیریتی',
                'ordering': ('-created_at',),
            },
        ),
    ]
