# Generated by Django 5.2.17 on 2026-08-24 14:47

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_adminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('fertilizer', 'کود'), ('pesticide', 'سم')], db_index=True, max_length=20)),
                ('active_ingredient', models.CharField(blank=True, max_length=150)),
                ('formulation', models.CharField(blank=True, max_length=100, verbose_name='فرمولاسیون')),
                ('unit', models.CharField(default='کیلوگرم', max_length=20, verbose_name='واحد اندازه\u200cگیری')),
                ('safety_notes', models.TextField(blank=True, max_length=1500, verbose_name='هشدارهای ایمنی')),
                ('preharvest_interval_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='دوره کارنس (روز)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نهاده کشاورزی',
                'verbose_name_plural': 'نهاده\u200cهای کشاورزی',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AgriInputDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=120, verbose_name='محصول هدف')),
                ('target', models.CharField(blank=True, max_length=150, verbose_name='آفت/نیاز هدف')),
                ('basis', models.CharField(choices=[('per_hectare', 'به ازای هکتار'), ('per_1000_liter', 'به ازای ۱۰۰۰ لیتر آب')], default='per_hectare', max_length=20)),
                ('min_rate', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='حداقل دوز')),
                ('max_rate', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='حداکثر دوز')),
                ('rate_unit', models.CharField(default='کیلوگرم', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'دوز مصرف نهاده',
                'verbose_name_plural': 'دوزهای مصرف نهاده',
                'ordering': ('crop_name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('kind', models.CharField(choices=[('province', 'استان'), ('city', 'شهر')], db_index=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'موقعیت جغرافیایی',
                'verbose_name_plural': 'موقعیت\u200cهای جغرافیایی',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StorefrontFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دنبال\u200cکننده غرفه',
                'verbose_name_plural': 'دنبال\u200cکنندگان غرفه',
            },
        ),
        migrations.CreateModel(
            name='StorefrontHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='storefront-highlights/%Y/%m/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هایلایت غرفه',
                'verbose_name_plural': 'هایلایت\u200cهای غرفه',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StorefrontHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.marketplacelisting'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='rejection_reason',
            field=models.TextField(blank=True, max_length=1000, verbose_name='دلیل رد آگهی'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kind',
            field=models.CharField(choices=[('product', 'محصول فروشگاه'), ('listing', 'آگهی غرفه')], db_index=True, default='product', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.marketplacelisting'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storefront',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.storefront'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storefront_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام غرفه'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storefront_slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='storefront',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='storefronts/%Y/%m/', verbose_name='تصویر غرفه'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='storefronts/covers/%Y/%m/', verbose_name='کاور غرفه'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='storefront',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سطح ۱ — خریدار'), (2, 'سطح ۲ — غرفه\u200cدار'), (3, 'سطح ۳ — ناظر محتوا'), (4, 'سطح ۴ — مدیر'), (5, 'سطح ۵ — مالک سیستم')], db_index=True, default=1, verbose_name='سطح دسترسی'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['status', '-created_at'], name='shop_market_status_5dfb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('cart', 'listing'), name='unique_cart_listing'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', True), ('product__isnull', False)), models.Q(('listing__isnull', False), ('product__isnull', True)), _connector='OR'), name='cart_item_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='agriinput',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agri_inputs', to='shop.product'),
        ),
        migrations.AddField(
            model_name='agriinputdose',
            name='agri_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='shop.agriinput'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.location'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefronts', to='shop.location'),
        ),
        migrations.AddConstraint(
            model_name='storefront',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_storefront_name_ci'),
        ),
        migrations.AddField(
            model_name='storefrontfollow',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='shop.storefront'),
        ),
        migrations.AddField(
            model_name='storefrontfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_storefronts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefronthighlight',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='shop.storefront'),
        ),
        migrations.AddField(
            model_name='storefronthighlightitem',
            name='highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.storefronthighlight'),
        ),
        migrations.AddField(
            model_name='storefronthighlightitem',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_items', to='shop.storefrontpost'),
        ),
        migrations.AddConstraint(
            model_name='agriinputdose',
            constraint=models.UniqueConstraint(fields=('agri_input', 'crop_name', 'target', 'basis'), name='unique_dose_per_input_crop_target'),
        ),
        migrations.AddConstraint(
            model_name='agriinputdose',
            constraint=models.CheckConstraint(condition=models.Q(('max_rate__gte', models.F('min_rate'))), name='dose_max_rate_gte_min_rate'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['kind', 'name'], name='shop_locati_kind_9a71cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_location_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='storefrontfollow',
            constraint=models.UniqueConstraint(fields=('storefront', 'user'), name='unique_storefront_follow'),
        ),
        migrations.AddConstraint(
            model_name='storefronthighlightitem',
            constraint=models.UniqueConstraint(fields=('highlight', 'post'), name='unique_highlight_post'),
        ),
    ]
