# Generated by Django 4.2.5 on 2024-01-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
