# Generated by Django 4.2.5 on 2025-07-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SeedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100, verbose_name='نوع گیاه')),
                ('variety', models.CharField(max_length=100, verbose_name='رقم')),
                ('weight_per_kg', models.CharField(max_length=20, verbose_name='وزن در کیلوگرم')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات بذر',
                'verbose_name_plural': 'مشخصات بذر',
            },
        ),
        migrations.CreateModel(
            name='PesticideDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_type', models.CharField(max_length=100, verbose_name='نوع سم')),
                ('active_ingredient', models.CharField(max_length=100, verbose_name='مواد فعال')),
                ('concentration', models.CharField(max_length=20, verbose_name='غلظت (%)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات سم',
                'verbose_name_plural': 'مشخصات سم',
            },
        ),
        migrations.CreateModel(
            name='FertilizerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(max_length=100, verbose_name='نوع کود')),
                ('nitrogen', models.CharField(max_length=20, verbose_name='نیتروژن (%)')),
                ('phosphorus', models.CharField(max_length=20, verbose_name='فسفر (%)')),
                ('potassium', models.CharField(max_length=20, verbose_name='پتاسیم (%)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات کود',
                'verbose_name_plural': 'مشخصات کود',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=100, verbose_name='نوع ابزار')),
                ('material', models.CharField(max_length=100, verbose_name='جنس')),
                ('weight', models.CharField(max_length=20, verbose_name='وزن')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات ابزار',
                'verbose_name_plural': 'مشخصات ابزار',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='دسته'),
        ),
    ]
