# Generated by Django 5.2.17 on 2026-08-24 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models




def _demo_offer_values(model, app_label):
    """Deterministic, varied discount/sales figures so the 'best sellers' and
    'most discounted' sections render meaningful data without manual setup."""
    rows = list(model.objects.all().order_by('id'))
    for index, row in enumerate(rows):
        cycle = index % 6
        row.discount_percent = (0, 0, 10, 15, 20, 30)[cycle]
        row.sales_count = (7 + index * 11) % 200
        row.save(update_fields=['discount_percent', 'sales_count'])


def _seed_locations(apps, schema_editor):
    """Load Iran's 31 provinces and their cities, mirroring the idempotent
    ``seed_locations`` command, so the checkout and storefront address forms
    always expose the complete geography."""
    from shop.data.iran_locations import IRAN_PROVINCES
    from shop.slugs import slugify_fa

    Location = apps.get_model('shop', 'Location')
    for province_name, cities in IRAN_PROVINCES.items():
        province, _ = Location.objects.update_or_create(
            name=province_name,
            parent=None,
            defaults={'kind': 'province', 'slug': slugify_fa(province_name), 'is_active': True},
        )
        for city_name in cities:
            Location.objects.update_or_create(
                name=city_name,
                parent=province,
                defaults={
                    'kind': 'city',
                    'slug': slugify_fa(f'{province_name}-{city_name}'),
                    'is_active': True,
                },
            )


def backfill_demo_data(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    MarketplaceListing = apps.get_model('shop', 'MarketplaceListing')
    _demo_offer_values(Product, 'shop')
    _demo_offer_values(MarketplaceListing, 'shop')


def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_backfill_levels_and_order_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.CreateModel(
            name='StorefrontConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_conversations', to=settings.AUTH_USER_MODEL)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='shop.storefront')),
            ],
            options={
                'verbose_name': 'گفتگوی غرفه',
                'verbose_name_plural': 'گفتگوهای غرفه',
            },
        ),
        migrations.CreateModel(
            name='StorefrontMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.storefrontconversation')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_messages', to='shop.marketplacelisting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_storefront_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام غرفه',
                'verbose_name_plural': 'پیام\u200cهای غرفه',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='storefrontconversation',
            constraint=models.UniqueConstraint(fields=('storefront', 'customer'), name='unique_storefront_customer_conversation'),
        ),
        migrations.AddIndex(
            model_name='storefrontmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='shop_storef_convers_6475fa_idx'),
        ),
        migrations.RunPython(backfill_demo_data, noop),
        migrations.RunPython(_seed_locations, noop),
    ]

