# Generated by Django 5.2.17 on 2026-08-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_storefront_messaging_and_offers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام زمین')),
                ('land_type', models.CharField(choices=[('orchard', 'باغ'), ('farmland', 'زمین زراعی'), ('greenhouse', 'گلخانه')], max_length=20, verbose_name='نوع زمین')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت')),
                ('area_unit', models.CharField(choices=[('hectare', 'هکتار'), ('jarib', 'جریب'), ('square_meter', 'مترمربع')], default='hectare', max_length=15, verbose_name='واحد مساحت')),
                ('crop_type', models.CharField(max_length=150, verbose_name='نوع محصول')),
                ('crop_variety', models.CharField(blank=True, max_length=150, verbose_name='رقم/واریته')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
                ('soil_type', models.CharField(choices=[('loam', 'لومی'), ('clay', 'رسی'), ('sandy', 'شنی'), ('calcareous', 'آهکی'), ('other', 'سایر')], default='loam', max_length=15, verbose_name='نوع خاک')),
                ('irrigation_type', models.CharField(choices=[('drip', 'قطره\u200cای'), ('sprinkler', 'بارانی'), ('flood', 'غرقابی'), ('furrow', 'کرتی/نشتی'), ('other', 'سایر')], default='drip', max_length=15, verbose_name='نوع آبیاری')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='تاریخ کاشت')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='یادداشت\u200cهای شناسنامه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_lands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'زمین کشاورز',
                'verbose_name_plural': 'زمین\u200cهای کشاورزان',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FarmConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('general', 'مشاوره عمومی'), ('spraying', 'مشاوره سم\u200cپاشی'), ('fertilizing', 'مشاوره کوددهی'), ('irrigation', 'مشاوره آبیاری'), ('pest', 'آفت و بیماری')], default='general', max_length=15, verbose_name='موضوع')),
                ('message', models.TextField(max_length=3000, verbose_name='متن درخواست')),
                ('reply', models.TextField(blank=True, max_length=3000, verbose_name='پاسخ مشاور')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('answered', 'پاسخ داده شد'), ('closed', 'بسته شد')], db_index=True, default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_consultations', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='shop.farmland')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره کشاورزی',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره کشاورزی',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FarmCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('spraying', 'سم\u200cپاشی'), ('fertilizing', 'کوددهی'), ('irrigation', 'آبیاری')], max_length=15, verbose_name='نوع عملیات')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ اجرا')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='دستورالعمل')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('done', 'انجام شد'), ('cancelled', 'لغو شد')], db_index=True, default='planned', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_farm_events', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='shop.farmland')),
            ],
            options={
                'verbose_name': 'رویداد تقویم کشاورزی',
                'verbose_name_plural': 'رویدادهای تقویم کشاورزی',
                'ordering': ('date', 'created_at'),
                'indexes': [models.Index(fields=['land', 'date'], name='shop_farmca_land_id_3459a1_idx')],
            },
        ),
    ]
