# Generated by Django 5.2.17 on 2026-08-25 13:36

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_farm_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='پنهان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نظر پست غرفه',
                'verbose_name_plural': 'نظرات پست غرفه',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorefrontPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پسند پست غرفه',
                'verbose_name_plural': 'پسندهای پست غرفه',
            },
        ),
        migrations.CreateModel(
            name='StorefrontStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازدید استوری',
                'verbose_name_plural': 'بازدیدهای استوری',
            },
        ),
        migrations.AlterModelOptions(
            name='storefrontconversation',
            options={'verbose_name': 'گفتگو', 'verbose_name_plural': 'گفتگوها'},
        ),
        migrations.AlterModelOptions(
            name='storefrontmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.RemoveConstraint(
            model_name='storefrontconversation',
            name='unique_storefront_customer_conversation',
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='channel',
            field=models.CharField(choices=[('storefront', 'غرفه'), ('support', 'پشتیبانی'), ('consulting', 'پشتیبانی کشاورزان'), ('comment', 'پاسخ به دیدگاه')], db_index=True, default='storefront', max_length=20, verbose_name='کانال'),
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.message_attachment_path, verbose_name='پیوست'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='attachment_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت (ثانیه)'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صدا')], max_length=10, verbose_name='نوع پیوست'),
        ),
        migrations.AlterField(
            model_name='storefrontconversation',
            name='storefront',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='shop.storefront'),
        ),
        migrations.AddConstraint(
            model_name='storefrontconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'storefront')), fields=('storefront', 'customer'), name='unique_storefront_customer_conversation'),
        ),
        migrations.AddConstraint(
            model_name='storefrontconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__in', ['support', 'consulting'])), fields=('customer', 'channel'), name='unique_customer_service_conversation'),
        ),
        migrations.AddConstraint(
            model_name='storefrontconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'storefront'), ('storefront__isnull', False)), models.Q(models.Q(('channel', 'storefront'), _negated=True), ('storefront__isnull', True)), _connector='OR'), name='storefront_channel_requires_storefront'),
        ),
        migrations.AddField(
            model_name='storefrontpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.storefrontpostcomment'),
        ),
        migrations.AddField(
            model_name='storefrontpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.storefrontpost'),
        ),
        migrations.AddField(
            model_name='storefrontpostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefrontpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shop.storefrontpost'),
        ),
        migrations.AddField(
            model_name='storefrontpostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_storefront_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefrontstoryview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='shop.storefrontpost'),
        ),
        migrations.AddField(
            model_name='storefrontstoryview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storefrontpostcomment',
            index=models.Index(fields=['post', 'created_at'], name='shop_storef_post_id_b2a440_idx'),
        ),
        migrations.AddConstraint(
            model_name='storefrontpostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_storefront_post_like'),
        ),
        migrations.AddConstraint(
            model_name='storefrontstoryview',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_story_view'),
        ),
    ]
