# Generated by Django 5.2.17 on 2026-09-03 02:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_storefrontpostcomment_storefrontpostlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید شماره تلفن'),
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('bale', 'بله'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ رسمی')], max_length=20)),
                ('destination', models.CharField(help_text='شناسه چت برای تلگرام/بله یا شماره E.164 برای پیامک/واتساپ.', max_length=200)),
                ('receive_order_created', models.BooleanField(default=True)),
                ('receive_order_status_changed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گیرنده پیام مدیریتی',
                'verbose_name_plural': 'گیرندگان پیام مدیریتی',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('channel', 'destination'), name='unique_notification_recipient')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام داخلی')),
                ('event', models.CharField(choices=[('order_created', 'سفارش جدید'), ('order_status_changed', 'تغییر وضعیت سفارش'), ('test', 'ارسال آزمایشی')], db_index=True, max_length=40)),
                ('audience', models.CharField(choices=[('owner', 'مالک/مدیر'), ('customer', 'مشتری'), ('seller', 'غرفه\u200cدار')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('bale', 'بله'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ رسمی')], max_length=20)),
                ('body', models.TextField(help_text='متغیرها با آکولاد نوشته می\u200cشوند؛ نمونه: {order_code} و {total_price}.', verbose_name='متن قالب')),
                ('provider_template_name', models.CharField(blank=True, help_text='نام قالب تأییدشده ارائه\u200cدهنده، مخصوصاً برای WhatsApp Cloud API.', max_length=160)),
                ('language_code', models.CharField(default='fa', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب پیام\u200cرسانی',
                'verbose_name_plural': 'قالب\u200cهای پیام\u200cرسانی',
                'ordering': ('event', 'audience', 'channel'),
                'constraints': [models.UniqueConstraint(fields=('event', 'audience', 'channel'), name='unique_notification_template_route')],
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('purpose', models.CharField(choices=[('login', 'ورود')], default='login', max_length=20)),
                ('code_hash', models.CharField(editable=False, max_length=128)),
                ('delivery_channel', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('verified', 'تأیید شده'), ('expired', 'منقضی شده'), ('failed', 'ناموفق/مسدود')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'status', '-created_at'], name='otp_phone_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('order_created', 'سفارش جدید'), ('order_status_changed', 'تغییر وضعیت سفارش'), ('test', 'ارسال آزمایشی')], db_index=True, max_length=40)),
                ('audience', models.CharField(choices=[('owner', 'مالک/مدیر'), ('customer', 'مشتری'), ('seller', 'غرفه\u200cدار')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('bale', 'بله'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ رسمی')], max_length=20)),
                ('recipient', models.CharField(max_length=200)),
                ('rendered_content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('processing', 'در حال ارسال'), ('retry', 'منتظر تلاش مجدد'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('failed', 'ناموفق نهایی')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=6)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='shop.order')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='shop.notificationtemplate')),
            ],
            options={
                'verbose_name': 'ارسال پیام',
                'verbose_name_plural': 'صف و تاریخچه ارسال پیام\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notify_due_idx'), models.Index(fields=['event', '-created_at'], name='notify_event_idx')],
            },
        ),
    ]
