# Generated by Django 5.2.17 on 2026-09-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_useraccount_phone_verified_at_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
