# Generated by Django 5.2.17 on 2026-09-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_seed_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
