# Generated by Django 5.2.17 on 2026-09-03 03:05

import re

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def resolve_ambiguous_phones(apps, schema_editor):
    """Keep one owner per legacy phone before enforcing OTP-safe uniqueness."""

    UserAccount = apps.get_model('shop', 'UserAccount')
    AdminAuditLog = apps.get_model('shop', 'AdminAuditLog')

    translation = str.maketrans(
        '۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩',
        '01234567890123456789',
    )
    for account in UserAccount.objects.exclude(phone='').iterator():
        digits = re.sub(r'\D', '', account.phone.translate(translation))
        if digits.startswith('0098'):
            digits = digits[4:]
        elif digits.startswith('98'):
            digits = digits[2:]
        if len(digits) == 10 and digits.startswith('9'):
            digits = f'0{digits}'
        if re.fullmatch(r'09\d{9}', digits) and account.phone != digits:
            account.phone = digits
            account.save(update_fields=['phone'])

    duplicates = (
        UserAccount.objects.exclude(phone='')
        .values('phone')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    for duplicate in duplicates.iterator():
        accounts = list(
            UserAccount.objects.filter(phone=duplicate['phone']).order_by(
                models.F('phone_verified_at').desc(nulls_last=True), 'id'
            )
        )
        # A previously verified association wins; otherwise the oldest one is
        # retained. Ambiguous rows are cleared rather than made OTP-eligible.
        for account in accounts[1:]:
            account.phone = ''
            account.phone_verified_at = None
            account.save(update_fields=['phone', 'phone_verified_at'])
            AdminAuditLog.objects.create(
                actor=None,
                action='duplicate_phone_cleared',
                target_type='UserAccount',
                target_id=str(account.pk),
                summary='شماره تکراری قدیمی پیش از فعال‌سازی ورود OTP پاک شد.',
                metadata={'retained_account_id': accounts[0].pk},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_onetimepassword_last_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(resolve_ambiguous_phones, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(
                condition=~models.Q(phone=''),
                fields=('phone',),
                name='unique_nonempty_useraccount_phone',
            ),
        ),
    ]
