# Generated by Django 5.2.17 on 2026-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_useraccount_unique_nonempty_useraccount_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'provider_message_id'], name='notify_provider_msg_idx'),
        ),
    ]
