# Generated by Django 5.2.17 on 2026-09-04 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_historicalcategory_historicalnotificationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='حذف در'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ویرایش در'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='shop.storefrontmessage', verbose_name='پاسخ به'),
        ),
    ]
