# Generated by Django 5.2.17 on 2026-09-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_brandpartner_historicalsitearticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, max_length=300, verbose_name='مقدار'),
        ),
    ]
