# Generated by Django 5.2.17 on 2026-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_productattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingattribute',
            name='value',
            field=models.CharField(blank=True, max_length=300, verbose_name='مقدار'),
        ),
    ]
