# Generated by Django 5.2.17 on 2026-09-05 22:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_listingattribute_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulting_start', models.TimeField(default=datetime.time(6, 0), verbose_name='شروع مشاوره')),
                ('consulting_end', models.TimeField(default=datetime.time(22, 0), verbose_name='پایان مشاوره')),
                ('support_start', models.TimeField(default=datetime.time(6, 0), verbose_name='شروع پشتیبانی')),
                ('support_end', models.TimeField(default=datetime.time(22, 0), verbose_name='پایان پشتیبانی')),
                ('work_days', models.CharField(default='0,1,2,3,4,5,6', help_text='روزهای کاری با ایندکس شنبه=۰ تا جمعه=۶، جدا شده با کاما.', max_length=40, verbose_name='روزهای کاری')),
                ('presence_minutes', models.PositiveSmallIntegerField(default=10, help_text='چند دقیقه فعالیت آخر یک کارشناس «آنلاین» حساب شود.', verbose_name='بازه حضور (دقیقه)')),
                ('out_of_hours_note', models.TextField(default='الان خارج از ساعت کاری هستیم. درخواستتان را همین\u200cجا بنویسید؛ در اولین بازه کاری بعدی پاسخ می\u200cدهیم.', max_length=400, verbose_name='پیام خارج از ساعت کاری')),
                ('is_active', models.BooleanField(default=True, help_text='خاموش کردن، نشانگر آنلاین/ساعت کاری را از چت حذف می\u200cکند.', verbose_name='نمایش وضعیت میز خدمت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات میز خدمت',
                'verbose_name_plural': 'تنظیمات میز خدمت',
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'کاربر / کشاورز'), ('staff', 'کارشناس میز')], default='customer', max_length=10)),
                ('channel', models.CharField(choices=[('any', 'همه میزها'), ('consulting', 'مشاوره کشاورزی'), ('support', 'پشتیبانی')], default='any', max_length=20, verbose_name='میز')),
                ('label', models.CharField(blank=True, help_text='متن دکمه؛ خالی بمانید خود متن استفاده می\u200cشود.', max_length=60, verbose_name='برچسب کوتاه')),
                ('text', models.CharField(max_length=400, verbose_name='متن پیام')),
                ('is_first_message_only', models.BooleanField(default=False, help_text='برای سؤالات متداولی که فقط بار اول لازم است.', verbose_name='فقط برای اولین پیام')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پاسخ آماده',
                'verbose_name_plural': 'پاسخ\u200cهای آماده',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بسته شد در'),
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='بسته شده توسط'),
        ),
        migrations.AddField(
            model_name='storefrontconversation',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده')], db_index=True, default='open', max_length=10, verbose_name='وضعیت گفتگو'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='shop.farmland', verbose_name='پرونده زمین'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='link_kind',
            field=models.CharField(blank=True, max_length=20, verbose_name='نوع لینک'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='link_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='متن لینک'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='link_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس لینک'),
        ),
        migrations.AlterField(
            model_name='storefrontmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_storefront_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeskAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('consulting', 'مشاور کشاورزی'), ('support', 'پشتیبانی')], default='support', max_length=20, verbose_name='میز')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='نام نمایشی')),
                ('title', models.CharField(blank=True, help_text='مثلاً «کارشناس ارشد تغذیه گیاه»', max_length=120, verbose_name='سمت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='desk/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, max_length=400, verbose_name='تخصص\u200cها و سوابق')),
                ('specialties', models.CharField(blank=True, help_text='مثلاً «سم\u200cپاشی، تغذیه، آبیاری» — برای تقسیم کار در صف.', max_length=200, verbose_name='حوزه\u200cها (با کاما)')),
                ('work_days', models.CharField(blank=True, max_length=40, verbose_name='روزهای کاری شخصی')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='شروع شیفت')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='پایان شیفت')),
                ('max_open_threads', models.PositiveSmallIntegerField(default=0, help_text='۰ یعنی بدون سقف.', verbose_name='سقف گفتگوی باز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='عضو فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_profiles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کارشناس')),
            ],
            options={
                'verbose_name': 'کارشناس میز خدمت',
                'verbose_name_plural': 'کارشناسان میز خدمت',
                'ordering': ('order', 'display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConversationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (۱ تا ۵)')),
                ('solved', models.BooleanField(blank=True, null=True, verbose_name='مشکل حل شد؟')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.storefrontconversation')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_ratings', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='shop.deskagent', verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'رضایت از گفتگو',
                'verbose_name_plural': 'نظرسنجی گفتگوها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='deskagent',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_desk_agent_user_role'),
        ),
        migrations.AddConstraint(
            model_name='conversationrating',
            constraint=models.UniqueConstraint(fields=('conversation', 'rater'), name='unique_rating_per_conversation'),
        ),
    ]
