# Generated by Django 5.2.17 on 2026-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_seed_desk_quick_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontmessage',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='اعلان سیستمی'),
        ),
    ]
