# Generated by Django 5.2.17 on 2026-09-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_storefrontmessage_is_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='legal_version',
            field=models.CharField(blank=True, max_length=40, verbose_name='نسخه متن حقوقی'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش شرایط'),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_version',
            field=models.CharField(blank=True, max_length=40, verbose_name='نسخه متن حقوقی'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش شرایط'),
        ),
    ]
