# Generated by Django 5.2.17 on 2026-09-06 00:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_historicalorder_legal_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(blank=True, max_length=64, verbose_name='کلید بازدیدکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رأی مفید بودن',
                'verbose_name_plural': 'رأی\u200cهای مفید بودن',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='نام برچسب')),
                ('slug', models.SlugField(max_length=90, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='توضیح')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='تصویر')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='توضیح متا')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical برچسب',
                'verbose_name_plural': 'historical برچسب\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='زیرنویس')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='نوع بسته\u200cبندی')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='وزن (کیلوگرم)')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (خالی = قیمت محصول)')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی (خالی = موجودی محصول)')),
                ('min_order_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل سفارش')),
                ('bulk_note', models.TextField(blank=True, max_length=500, verbose_name='توضیح فروش فله')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بسته\u200cبندی محصول',
                'verbose_name_plural': 'بسته\u200cبندی\u200cهای محصول',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مهلت بازگشت (روز)')),
                ('conditions', models.TextField(blank=True, help_text='شرایطی که در همان صفحه حقوقی و زیر بنر پاورقی نمایش داده می\u200cشود.', max_length=1500, verbose_name='شرایط بازگشت کالا')),
                ('express_shipping_enabled', models.BooleanField(default=False, help_text='گزینه «تحویل فوری» را در انتخاب روش ارسال فعال می\u200cکند.', verbose_name='ارسال فوری در سبد خرید')),
                ('express_shipping_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه اضافی ارسال فوری (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سیاست بازگشت کالا',
                'verbose_name_plural': 'تنظیمات سیاست بازگشت کالا',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='توضیح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='تصویر')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='توضیح متا')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='comment',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='رأی مفید بودن'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='نمایش در تجربه خرید مشتریان'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False, verbose_name='گزارش\u200cشده'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='bulk_note',
            field=models.TextField(blank=True, max_length=500, verbose_name='توضیح فروش فله'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل سفارش'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولید'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='video_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='ویدئوی معرفی'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='بسته\u200cبندی فروخته\u200cشده'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_note',
            field=models.TextField(blank=True, max_length=500, verbose_name='توضیح فروش فله'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل سفارش'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولید'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='ویدئوی معرفی'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='shop.comment', verbose_name='نظر'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shop.productpackage', verbose_name='بسته\u200cبندی'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('product_package__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_without_package'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_package__isnull', False)), fields=('cart', 'product', 'product_package'), name='unique_cart_product_package'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_helpful_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='productpackage',
            constraint=models.UniqueConstraint(fields=('product', 'label'), name='unique_product_package_label'),
        ),
    ]
