# Generated by Django 5.2.17 on 2026-09-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_brandpartner_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepageblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'سرتیتر'), ('text', 'متن'), ('bullets', 'فهرست موردی'), ('image', 'تصویر'), ('spec_table', 'جدول مشخصات'), ('price_table', 'جدول قیمت'), ('video', 'ویدئو'), ('products', 'شبکه محصولات'), ('articles', 'شبکه مقالات'), ('cta', 'دکمه اقدام'), ('quote', 'نقل\u200cقول'), ('faq', 'پرسش و پاسخ')], default='text', max_length=15, verbose_name='نوع بلوک'),
        ),
    ]
