# Generated by Django 5.2.17 on 2026-09-06 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_sitepageblock_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('auto', 'تطبیقی با توان سرور'), ('fixed', 'عدد ثابت (دستی)')], default='auto', max_length=8, verbose_name='روش تعیین ظرفیت')),
                ('fixed_limit', models.PositiveIntegerField(blank=True, help_text='فقط در روش دستی استفاده می\u200cشود؛ تعداد نفرانی که هم\u200cزمان داخل سایت می\u200cمانند.', null=True, verbose_name='سقف دستی')),
                ('users_per_cpu_core', models.PositiveSmallIntegerField(default=80, help_text='تخمین نفر به\u200cازای هر هسته پردازنده، پیش از کسر ضریب اطمینان.', verbose_name='کاربر به\u200cازای هر هسته')),
                ('users_per_gb_ram', models.PositiveSmallIntegerField(default=40, help_text='تخمین نفر به\u200cازای هر گیگابایت حافظه\u200cی آزادِ در دسترس این پروسه.', verbose_name='کاربر به\u200cازای هر گیگابایت')),
                ('safety_percent', models.PositiveSmallIntegerField(default=75, help_text='سهمی از توان اندازه\u200cگیری\u200cشده که واقعاً به بازدیدکننده داده می\u200cشود؛ بقیه برای کرنل، دیتابیس و جاهای غیرمنتظره می\u200cماند.', verbose_name='ضریب اطمینان (٪)')),
                ('derate_load_percent', models.PositiveSmallIntegerField(default=150, help_text='اگر بار یک\u200cدقیقه\u200cای هر هسته از این درصد بگذرد، سقف همان لحظه به همان نسبت کم می\u200cشود؛ یعنی وقتی خودِ ماشین زیر فشار است، صف زودتر شروع می\u200cشود.', verbose_name='آستانه فشار (٪ بار هر هسته)')),
                ('activity_window_minutes', models.PositiveSmallIntegerField(default=5, help_text='چند دقیقه از آخرین درخواست یک نفر، او را «آنلاین» حساب می\u200cکند.', verbose_name='بازه حضور (دقیقه)')),
                ('sample_interval_seconds', models.PositiveSmallIntegerField(default=60, help_text='چند وقت یک\u200cبار وضعیت سرور نمونه\u200cبرداری و در نمودار ثبت می\u200cشود.', verbose_name='بازه نمونه\u200cبرداری (ثانیه)')),
                ('queue_enabled', models.BooleanField(default=False, help_text='با روشن\u200cکردن، بازدیدکننده\u200cی تازه\u200cای که جایی نمانده به صفحه انتظار می\u200cرود و هرچه باز می\u200cشود به ترتیب ورودش داخل می\u200cآید.', verbose_name='صف انتظار')),
                ('queue_max_minutes', models.PositiveSmallIntegerField(default=30, help_text='پس از این مدت در صف، کاربر بدون توجه به ظرفیت وارد می\u200cشود؛ هیچ\u200cکس تا ابدیدر صف نمی\u200cماند.', verbose_name='حداکثر ماندن در صف (دقیقه)')),
                ('queue_message', models.TextField(blank=True, help_text='متنی که کاربر در صفحه انتظار می\u200cخواند. خالی بماند، پیام پیش\u200cفرض نمایش داده می\u200cشود.', max_length=600, verbose_name='پیام صفحه انتظار')),
                ('bypass_staff', models.BooleanField(default=True, help_text='کارمندان و مدیران هرگز در صف نمی\u200cمانند تا بتوانند سایت را درست کنند.', verbose_name='عبور کارکنان از صف')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات ظرفیت و صف',
                'verbose_name_plural': 'تنظیمات ظرفیت و صف',
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='کلید صف')),
                ('status', models.CharField(choices=[('waiting', 'در صف'), ('admitted', 'وارد شده')], db_index=True, default='waiting', max_length=10)),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='صفحه\u200cی درخواستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ورود به صف')),
                ('admitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('waits', models.PositiveIntegerField(default=1, help_text='چند بار پشت\u200cدرپیش به صفحه انتظار برگشته است؛ برای اینکه کسی با رفراف\u200cکردن جلوتر نزند.', verbose_name='تعداد مراجعه')),
            ],
            options={
                'verbose_name': 'بلیت صف',
                'verbose_name_plural': 'بلیت\u200cهای صف',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ResourceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='هسته\u200cها')),
                ('load_1m', models.FloatField(blank=True, null=True, verbose_name='بار یک\u200cدقیقه\u200cای')),
                ('load_5m', models.FloatField(blank=True, null=True, verbose_name='بار پنج\u200cدقیقه\u200cای')),
                ('memory_total_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='حافظه کل (مگابایت)')),
                ('memory_available_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='حافظه آزاد')),
                ('container_limit_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف حافظه کانتینر')),
                ('disk_free_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='فضای آزاد دیسک')),
                ('disk_total_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='فضای کل دیسک')),
                ('gpu', models.CharField(blank=True, max_length=140, verbose_name='پردازنده گرافیکی')),
                ('online_users', models.PositiveIntegerField(default=0, verbose_name='کاربران آنلاین')),
                ('online_guests', models.PositiveIntegerField(default=0, verbose_name='مهمان\u200cهای آنلاین')),
                ('queue_waiting', models.PositiveIntegerField(default=0, verbose_name='در صف')),
                ('capacity_limit', models.PositiveIntegerField(default=0, verbose_name='سقف استفاده\u200cشده')),
                ('capacity_basis', models.CharField(blank=True, max_length=220, verbose_name='نحوه محاسبه')),
            ],
            options={
                'verbose_name': 'نمونه وضعیت سرور',
                'verbose_name_plural': 'نمونه\u200cهای وضعیت سرور',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, help_text='اثر انگشت یکسان برای رویدادهای تکراری؛ یک ردیف، یک مشکل.', max_length=40, unique=True, verbose_name='گروه')),
                ('level', models.CharField(choices=[('error', 'خطا'), ('warning', 'هشدار'), ('notice', 'ثبت')], db_index=True, default='error', max_length=7)),
                ('source', models.CharField(db_index=True, max_length=70, verbose_name='بخش')),
                ('title', models.CharField(max_length=200, verbose_name='خلاصه')),
                ('message', models.TextField(blank=True, max_length=4000, verbose_name='جزئیات')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='نشانی')),
                ('method', models.CharField(blank=True, max_length=8, verbose_name='روش')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='کد وضعیت')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تکرار')),
                ('first_at', models.DateTimeField(auto_now_add=True, verbose_name='نخستین بار')),
                ('last_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='آخرین بار')),
                ('user_label', models.CharField(blank=True, max_length=120, verbose_name='نام کاربر در زمان رخداد')),
                ('visitor_key', models.CharField(blank=True, max_length=64, verbose_name='کلید بازدیدکننده')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='بافت')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='برطرف شد')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='یادداشت رفع')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_logs', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رویداد سامانه',
                'verbose_name_plural': 'رویدادهای سامانه',
                'ordering': ('-last_at',),
            },
        ),
        migrations.CreateModel(
            name='PresenceBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=90, unique=True, verbose_name='شناسه نشست')),
                ('kind', models.CharField(choices=[('user', 'کاربر'), ('guest', 'مهمان')], db_index=True, max_length=5)),
                ('is_staff', models.BooleanField(default=False, verbose_name='از کارکنان')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='آخرین نشانی')),
                ('requests', models.PositiveIntegerField(default=1, verbose_name='درخواست\u200cها در این بازه')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع این نشست')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='آخرین فعالیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_beats', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حضور کاربر',
                'verbose_name_plural': 'حضور کاربران',
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['kind', 'last_seen_at'], name='shop_presen_kind_6f351c_idx')],
            },
        ),
    ]
