# Generated by Django 5.2.17 on 2026-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_useraccount_eight_step_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='واریانت\u200cهای بهینه تصویر'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='واریانت\u200cهای بهینه تصویر'),
        ),
    ]
