# Generated by Django 5.2.17 on 2026-09-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_historicalproduct_image_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='واریانت\u200cهای بهینه تصویر'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='واریانت\u200cهای بهینه تصویر'),
        ),
    ]
