# Generated by Django 5.2.17 on 2026-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_marketplacelisting_image_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='loyalty_discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز وفاداری'),
        ),
    ]
