# Generated by Django 5.2.17 on 2026-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_historicalorder_loyalty_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('process_image', 'بازتولید واریانت\u200cهای تصویر'), ('send_otp', 'ارسال کد یک\u200cبارمصرف'), ('send_notification', 'ارسال نوتیفیکیشن')], db_index=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال اجرا'), ('completed', 'انجام\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تسک پس\u200cزمینه (Outbox)',
                'verbose_name_plural': 'تسک\u200cهای پس\u200cزمینه (Outbox)',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='outboxtask_poll_idx')],
            },
        ),
    ]
