# Generated by Django 5.2.17 on 2026-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_product_status_publish_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='loyalty_refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxtask',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('awaiting_review', 'در انتظار بررسی'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], db_index=True, default='awaiting_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_review', 'در انتظار بررسی'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], db_index=True, default='awaiting_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('loyalty_reward', 'پاداش وفاداری'), ('loyalty_refund', 'بازگشت امتیاز وفاداری'), ('order_discount', 'تخفیف سفارش'), ('refund', 'بازگشت وجه'), ('affiliate_payout', 'تسویه همکاری در فروش'), ('seller_payout', 'تسویه فروشنده'), ('adjustment', 'اصلاحیه')], max_length=30),
        ),
    ]
