# Generated by Django 5.2.17 on 2026-09-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_order_order_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=140, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='brand_slug',
            field=models.SlugField(blank=True, max_length=140, verbose_name='اسلاگ برند'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='shop.category', verbose_name='دسته آگهی'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='is_stock',
            field=models.BooleanField(db_index=True, default=False, verbose_name='کالای استوک'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='package_size',
            field=models.CharField(blank=True, db_index=True, help_text='مثلاً «کارتن ۱۰ کیلویی» یا «گونی ۵۰ کیلویی».', max_length=60, verbose_name='بسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='shop.subcategory', verbose_name='زیردسته آگهی'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='storefrontmessage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='shop.storefrontpost', verbose_name='پست پیوست\u200cشده'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='national_id_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید کد ملی'),
        ),
    ]
