# Generated by Django 5.2.17 on 2026-09-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_listing_catalog_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='storefront_only',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فقط در بازار غرفه\u200cداران'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='storefront_only',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فقط در بازار غرفه\u200cداران'),
        ),
    ]
