# Generated by Django 5.2.17 on 2026-09-10 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_marketplace_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontmessage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='shop.farmconsultationrequest', verbose_name='درخواست مشاوره'),
        ),
    ]
