# Generated by Django 5.2.17 on 2026-09-12 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_storefrontmessage_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='حداقل تعداد')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.marketplacelisting', verbose_name='آگهی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پله تخفیف',
                'verbose_name_plural': 'پله\u200cهای تخفیف',
                'ordering': ['min_quantity'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', True), ('product__isnull', False)), models.Q(('listing__isnull', False), ('product__isnull', True)), _connector='OR'), name='price_tier_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'min_quantity'), name='unique_price_tier_product_threshold'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('listing', 'min_quantity'), name='unique_price_tier_listing_threshold'), models.CheckConstraint(condition=models.Q(('min_quantity__gte', 2)), name='price_tier_min_quantity_at_least_two'), models.CheckConstraint(condition=models.Q(('discount_percent__gte', 1), ('discount_percent__lte', 100)), name='price_tier_discount_between_1_and_100')],
            },
        ),
    ]
