# Generated by Django 5.2.17 on 2026-09-13 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_price_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='rules_accepted',
            field=models.BooleanField(default=False, verbose_name='پذیرش قوانین غرفه\u200cداری'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پذیرش قوانین'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='برداشت ناخالص از موجودی قابل تسویه.')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='نرخ کمیسیون در لحظه درخواست.', max_digits=5)),
                ('commission_amount', models.PositiveBigIntegerField(help_text='کمیسیون پلتفرم از این برداشت.')),
                ('net_amount', models.PositiveBigIntegerField(help_text='مبلغ واریزی به کارت فروشنده.')),
                ('card_number', models.CharField(help_text='کارت مقصد واریز.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('paid', 'واریز شده به کارت'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='shop.storefront')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ('-created_at',),
            },
        ),
    ]
