# Generated by Django 5.2.17 on 2026-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_storefront_card_number_storefront_rules_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'مفید'), (-1, 'غیرمفید')], default=1, verbose_name='جهت رأی'),
        ),
    ]
