# Generated by Django 5.2.17 on 2026-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_commentvote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='helpful_count',
            field=models.IntegerField(default=0, verbose_name='امتیاز مفید بودن (مثبت/منفی)'),
        ),
    ]
