# Generated by Django 5.2.17 on 2026-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_comment_helpful_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, max_length=80, verbose_name='متن بالای عنوان')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('cta_url', models.CharField(blank=True, max_length=300, verbose_name='لینک دکمه (مثل /products)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/%Y/%m/', verbose_name='تصویر پس\u200cزمینه')),
                ('gradient', models.CharField(blank=True, max_length=200, verbose_name='کلاس گرادیان (بدون عکس)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ('order', 'id'),
            },
        ),
    ]
