# Generated by Django 5.2.17 on 2026-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='seller_type',
            field=models.CharField(choices=[('farmer', 'کشاورز'), ('cooperative', 'تعاونی'), ('merchant', 'تاجر'), ('company', 'شرکت'), ('agro_shop', 'مغازه سموم و نهاده\u200cهای کشاورزی')], default='farmer', max_length=20),
        ),
    ]
