# Generated by Django 5.2.17 on 2026-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_storefront_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='seller_type',
            field=models.CharField(choices=[('farmer', 'کشاورز'), ('cooperative', 'تعاونی'), ('merchant', 'تاجر'), ('company', 'شرکت'), ('agro_shop', 'نهاده\u200cهای کشاورزی')], default='farmer', max_length=20),
        ),
    ]
