# Generated by Django 5.2.17 on 2026-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_storefront_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولید'),
        ),
    ]
