# Generated by Django 5.2.17 on 2026-09-22 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_marketplacelisting_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontPostSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_marks', to='shop.storefrontpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست دیده\u200cشده',
                'verbose_name_plural': 'پست\u200cهای دیده\u200cشده',
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='unique_post_seen')],
            },
        ),
    ]
