# Generated by Django 5.2.17 on 2026-09-22 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_storefrontpostseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontmessage',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='shop.servicerequest', verbose_name='درخواست خدمت'),
        ),
    ]
