# Generated by Django 5.2.17 on 2026-09-22 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_storefrontmessage_service_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='shop.farmland', verbose_name='پرونده زمین'),
        ),
    ]
