# Generated by Django 5.2.17 on 2026-09-22 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_servicerequest_land'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storefrontconversation',
            name='unique_customer_service_conversation',
        ),
        migrations.AlterField(
            model_name='storefrontconversation',
            name='channel',
            field=models.CharField(choices=[('storefront', 'غرفه'), ('support', 'پشتیبانی'), ('consulting', 'پشتیبانی کشاورزان'), ('comment', 'پاسخ به دیدگاه'), ('procurement', 'خرید محصولات کشاورزان')], db_index=True, default='storefront', max_length=20, verbose_name='کانال'),
        ),
        migrations.AddConstraint(
            model_name='storefrontconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__in', ['support', 'consulting', 'procurement'])), fields=('customer', 'channel'), name='unique_customer_service_conversation'),
        ),
    ]
