# Generated by Django 5.2.17 on 2026-09-08 01:59

import django.core.validators
import django.db.models.deletion
import export.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0039_historicalorder_loyalty_refunded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(choices=[('IQ', 'عراق'), ('AE', 'امارات متحده عربی'), ('TR', 'ترکیه'), ('RU', 'روسیه'), ('AF', 'افغانستان'), ('PK', 'پاکستان'), ('AZ', 'جمهوری آذربایجان'), ('AM', 'ارمنستان'), ('KZ', 'قزاقستان'), ('TM', 'ترکمنستان'), ('OM', 'عمان'), ('QA', 'قطر'), ('KW', 'کویت'), ('CN', 'چین'), ('IN', 'هند')], db_index=True, max_length=2, verbose_name='کشور مقصد')),
                ('currency', models.CharField(choices=[('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('AED', 'درهم امارات'), ('IRT', 'تومان ایران')], default='USD', max_length=3, verbose_name='ارز توافق\u200cشده')),
                ('total_value_foreign', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ارزش کل به ارز توافق\u200cشده')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_docs', 'در انتظار اسناد'), ('customs_clearance', 'در حال ترخیص گمرکی'), ('shipped', 'ارسال شد'), ('completed', 'تکمیل شد')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت پرونده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_details', to='shop.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرونده صادراتی',
                'verbose_name_plural': 'پرونده\u200cهای صادراتی',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('commercial_invoice', 'فاکتور تجاری'), ('certificate_of_origin', 'گواهی مبدأ'), ('phytosanitary', 'گواهی بهداشت گیاهی'), ('packing_list', 'لیست بسته\u200cبندی')], max_length=24, verbose_name='نوع سند')),
                ('file', models.FileField(upload_to=export.models.export_document_upload_to, verbose_name='فایل سند')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='تأیید کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='export.exportorder', verbose_name='پرونده صادراتی')),
            ],
            options={
                'verbose_name': 'سند گمرکی',
                'verbose_name_plural': 'اسناد گمرکی',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='exportorder',
            index=models.Index(fields=['status', 'destination_country'], name='export_status_country_idx'),
        ),
    ]
