# Generated by Django 5.2.17 on 2026-09-07 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0038_product_product_status_publish_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(max_length=120, verbose_name='ماده مؤثره')),
                ('npk_ratio', models.CharField(help_text='به\u200cصورت سه\u200cبخشی با خط تیره؛ مثل 20-20-20', max_length=20, verbose_name='نسبت N-P-K')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='تاریخ انقضا')),
                ('registration_number', models.CharField(max_length=40, unique=True, verbose_name='شماره ثبت جهاد کشاورزی')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'کود',
                'verbose_name_plural': 'کودها',
                'ordering': ('expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_pest', models.CharField(max_length=150, verbose_name='آفت هدف')),
                ('toxicity_level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], db_index=True, default='medium', max_length=10, verbose_name='سطح سمیت')),
                ('waiting_period', models.PositiveSmallIntegerField(verbose_name='دوره کارنس (روز)')),
                ('registration_number', models.CharField(max_length=40, unique=True, verbose_name='شماره ثبت جهاد کشاورزی')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'سم',
                'verbose_name_plural': 'سموم',
                'ordering': ('product_id',),
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germination_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نرخ جوانه\u200cزنی (درصد)')),
                ('planting_season', models.CharField(choices=[('spring', 'بهار'), ('autumn', 'پاییز'), ('both', 'هر دو فصل')], db_index=True, default='spring', max_length=10, verbose_name='فصل کاشت')),
                ('seed_treatment', models.BooleanField(default=False, verbose_name='ضدعفونی\u200cشده')),
                ('variety_name', models.CharField(max_length=120, verbose_name='نام رقم')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seed_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'بذر',
                'verbose_name_plural': 'بذرها',
                'ordering': ('variety_name',),
            },
        ),
        migrations.CreateModel(
            name='Seedling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootstock', models.CharField(max_length=120, verbose_name='پایه')),
                ('scion_variety', models.CharField(max_length=120, verbose_name='رقم پیوندی')),
                ('age_years', models.PositiveSmallIntegerField(verbose_name='سن نهال (سال)')),
                ('height_cm', models.PositiveSmallIntegerField(verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_details', to='shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'نهال',
                'verbose_name_plural': 'نهال\u200cها',
                'ordering': ('product_id',),
            },
        ),
    ]
