# Generated by Django 5.2.17 on 2026-09-07 23:34

import agri_inputs.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_inputs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='expiry_date',
            field=models.DateField(db_index=True, validators=[agri_inputs.validators.validate_expiry_not_past], verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='germination_rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نرخ جوانه\u200cزنی (درصد)'),
        ),
    ]
