# Generated by Django 5.2.17 on 2026-09-07 23:48

import agri_inputs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_inputs', '0002_alter_fertilizer_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True, validators=[agri_inputs.validators.validate_expiry_not_past], verbose_name='تاریخ انقضا'),
        ),
    ]
