# Generated by Django 5.2.17 on 2026-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_inputs', '0003_pesticide_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='seed_treatment',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ضدعفونی\u200cشده'),
        ),
        migrations.AlterField(
            model_name='seedling',
            name='age_years',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='سن نهال (سال)'),
        ),
    ]
