"""Domain-split shop models. Pre-split import contract preserved:
    from shop.models import Product          # still works
    from shop import models; models.Product  # still works
"""

from .core import (
    Location,
    AdminAuditLog,
)
from .accounts import (
    UserAccount,
    account_level,
)
from .catalog import (
    PRODUCT_ATTRIBUTE_TEMPLATE,
    ProductManager,
    Category,
    SubCategory,
    Product,
    Tag,
    ProductImage,
    ProductPackage,
    PriceTier,
    FertilizerDetail,
    PesticideDetail,
    SeedDetail,
    EquipmentDetail,
    Comment,
    ProductAttribute,
    ListingAttribute,
)
from .outbox import OutboxTask
from .orders import (
    Cart,
    CartItem,
    create_reference,
    create_order_code,
    create_service_code,
    create_procurement_code,
    Order,
    OrderItem,
    Shipment,
    ShipmentTrackingEvent,
    ServiceRequest,
    ProcurementRequest,
)
from .marketplace import (
    Storefront,
    StorefrontFollow,
    StorefrontHighlight,
    StorefrontHighlightItem,
    MarketplaceListing,
)
from .payments import (
    PaymentAttempt,
    AffiliateProfile,
    AffiliateConversion,
    FinancialLedgerEntry,
    Coupon,
    Wallet,
    WalletTransaction,
)
from .trust import (
    PlatformFeedback,
    StorefrontComplaint,
    VisualSearchRequest,
)
from .social import (
    StorefrontPost,
    StorefrontPostLike,
    StorefrontPostComment,
    StorefrontStoryView,
    StorefrontConversation,
    message_attachment_path,
    StorefrontMessage,
)
from .farming import (
    FarmLand,
    FarmCalendarEvent,
    FarmConsultationRequest,
    AgriInput,
    AgriInputDose,
)
from .messaging import (
    OneTimePassword,
    NotificationTemplate,
    WebPushSubscription,
    NotificationRecipient,
    NotificationDelivery,
)
from .content import (
    SiteArticle,
    Service,
    SitePage,
    SitePageBlock,
    TeamMember,
    BrandPartner,
    SiteContact,
    NewsletterSubscriber,
)
from .desk import (
    DeskSettings,
    DeskAgent,
    QuickReply,
    ConversationRating,
    CommentVote,
    ReturnPolicySettings,
)
from .ops import (
    CapacitySettings,
    ResourceSample,
    PresenceBeat,
    QueueTicket,
    SystemLogEntry,
)

__all__ = [
    "PRODUCT_ATTRIBUTE_TEMPLATE",
    "OutboxTask",
    "Location",
    "AdminAuditLog",
    "UserAccount",
    "account_level",
    "ProductManager",
    "Category",
    "SubCategory",
    "Product",
    "Tag",
    "ProductImage",
    "ProductPackage",
    "PriceTier",
    "FertilizerDetail",
    "PesticideDetail",
    "SeedDetail",
    "EquipmentDetail",
    "Comment",
    "ProductAttribute",
    "ListingAttribute",
    "Cart",
    "CartItem",
    "create_reference",
    "create_order_code",
    "create_service_code",
    "create_procurement_code",
    "Order",
    "OrderItem",
    "Shipment",
    "ShipmentTrackingEvent",
    "ServiceRequest",
    "ProcurementRequest",
    "Storefront",
    "StorefrontFollow",
    "StorefrontHighlight",
    "StorefrontHighlightItem",
    "MarketplaceListing",
    "PaymentAttempt",
    "AffiliateProfile",
    "AffiliateConversion",
    "FinancialLedgerEntry",
    "Coupon",
    "Wallet",
    "WalletTransaction",
    "PlatformFeedback",
    "StorefrontComplaint",
    "VisualSearchRequest",
    "StorefrontPost",
    "StorefrontPostLike",
    "StorefrontPostComment",
    "StorefrontStoryView",
    "StorefrontConversation",
    "message_attachment_path",
    "StorefrontMessage",
    "FarmLand",
    "FarmCalendarEvent",
    "FarmConsultationRequest",
    "AgriInput",
    "AgriInputDose",
    "OneTimePassword",
    "NotificationTemplate",
    "WebPushSubscription",
    "NotificationRecipient",
    "NotificationDelivery",
    "SiteArticle",
    "Service",
    "SitePage",
    "SitePageBlock",
    "TeamMember",
    "BrandPartner",
    "SiteContact",
    "NewsletterSubscriber",
    "DeskSettings",
    "DeskAgent",
    "QuickReply",
    "ConversationRating",
    "CommentVote",
    "ReturnPolicySettings",
    "CapacitySettings",
    "ResourceSample",
    "PresenceBeat",
    "QueueTicket",
    "SystemLogEntry",
]
